# Generated by Django 4.1.4 on 2023-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='4544dfe2d7a24d9', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
