# Generated by Django 4.1.4 on 2023-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='0b21f4f1d5db4f6', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
