# Generated by Django 4.1.4 on 2023-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='553f39562c8f480', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
