# Generated by Django 4.1.4 on 2023-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='7f62b25c919b489', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
