# Generated by Django 4.1.4 on 2023-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0010_alter_user_id_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='2bedec5fe1de47f', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
