# Generated by Django 4.1.4 on 2023-04-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0014_alter_user_id_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='9c07bf740018470', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
    ]
