# Generated by Django 4.1.4 on 2023-04-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0015_alter_user_id_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='adeba32726964ce', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
