# Generated by Django 4.1.4 on 2023-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='d66fa7a8627078f9f23d335ef3bd1fa264b06861337e748d98c1df2e20e2926f', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
