# Generated by Django 4.1.4 on 2023-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0002_song_category_song_duration'),
        ('authz', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ManyToManyField(related_name='LikedSong', to='song.song')),
                ('user', models.ManyToManyField(related_name='user', to='authz.user')),
            ],
        ),
    ]
