# Generated by Django 4.1.4 on 2023-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0006_alter_user_id'),
        ('likedSong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedsong',
            name='user',
            field=models.ManyToManyField(related_name='LikedSong', to='authz.user'),
        ),
    ]
