# Generated by Django 4.1.4 on 2023-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(related_name='song', to='category.category'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
