# Generated by Django 4.1.4 on 2023-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_category_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
