# Generated by Django 4.1.4 on 2023-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
