# Generated by Django 4.1.4 on 2023-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='picURL',
            field=models.CharField(default='', max_length=150),
        ),
    ]
