# Generated by Django 4.1.4 on 2023-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='imageURL',
            field=models.CharField(default='', max_length=100),
        ),
    ]
